kubectl:
  remove_existing: false
  fallback_ver: v1.21.2

kustomize:
  remove_existing: false
  ver: v4.2.0

helm:
  remove_existing: false
  ver: v3.6.2

istioctl:
  remove_existing: false
  install: https://istio.io/downloadIstioctl

linkerd:
  remove_existing: false
  install: https://run.linkerd.io/install
