name: AZ-TF-BASE Destroy
on:   
  workflow_dispatch:

jobs:
  azbase:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: azure-iac/terraform/az-base    
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ secrets.TF_VERSION }}

      - name: Terraform version
        run: terraform version

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

      # Initialize with remote state
      - name: Terraform Init
        id: init
        run: |
          terraform init -backend-config="resource_group_name=${{ secrets.TF_BASE_RG_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.TF_BASE_SG_ACCT_NAME }}" \
          -backend-config="container_name=${{ secrets.TF_BASE_SG_CONTAINER_NAME }}" \
          -backend-config="key=${{ secrets.TF_BASE_STATE_KEY }}" 
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_winuser: ${{ secrets.TF_VAR_WINUSER }}
          TF_VAR_winpass: ${{ secrets.TF_VAR_WINPASS }}

      # Apply
      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  
  azbase-gw:
    runs-on: ubuntu-latest
    needs: azbase
    defaults:
      run:
        shell: bash
        working-directory: azure-iac/terraform/az-base-gw  
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ secrets.TF_VERSION }}

      - name: Terraform version
        run: terraform version

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

      # Initialize with remote state
      - name: Terraform Init
        id: init
        run: |
          terraform init -backend-config="resource_group_name=${{ secrets.TF_BASE_RG_NAME }}" \
          -backend-config="storage_account_name=${{ secrets.TF_BASE_SG_ACCT_NAME }}" \
          -backend-config="container_name=${{ secrets.TF_BASE_SG_CONTAINER_NAME }}" \
          -backend-config="key=${{ secrets.TF_BASE_GW_STATE_KEY }}" 
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}          

      # Apply
      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
